<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-08 08:41
=======
# Generated by Django 4.2.3 on 2023-08-08 08:10
>>>>>>> 88b8ce64cfeda8b21753e441b88e00f2674e4189

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streat_flavorites', '0003_item_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/'),
        ),
    ]
