# Generated by Django 4.2.3 on 2023-08-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streat_flavorites', '0004_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
