# Generated by Django 4.2.3 on 2023-08-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streat_flavorites', '0005_item_weight_grams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='weight_grams',
            new_name='weight',
        ),
    ]
